Improve debuggability of vscanim scripts (#1)
Introduce two command line flags, `--start-label`, and `--stop-label`
that enable you to specify a start and stop vscanim block, which allows
you to test a subset of the animation commands. To run vscanim on the
roots exercise, for example:
```
./vscanim.py intro-to-python.md --start-label=roots-exercise
```

Introduce an override flag for the global delay, so that you can slow
down an animation. For example to set the delay between animation
commands to be 2 seconds instead of the default of 0.5:
```
./vscanim.py intro-to-python.md --delay=2
```

Introduce a verbosity flag. Passing it once will print out the vscanim
command as they are executed. Passing it a second time will further
print out the osascript command. Here's some sample output for:

```
$ ./vscanim.py intro-to-python.md --start-label=roots-exercise -v
> VscAnim Command: clear_canvas()
> VscAnim Command: type("a = 1")
> VscAnim Command: type("b = -8")
> VscAnim Command: type("c = 12")
> VscAnim Command: type("r1", return_after=False)      # r1
> VscAnim Command: type(" = (", return_after=False)    # equals parens
> VscAnim Command: type("-b", return_after=False)      # minus b
> VscAnim Command: type(" + (", return_after=False)    # plus parens
> VscAnim Command: type("b**2", return_after=False)    # b squared
> VscAnim Command: type(" - 4", return_after=False)    # minus four
> VscAnim Command: type(" * a", return_after=False)    # times a
> VscAnim Command: type(" * c", return_after=False)    # times c
> VscAnim Command: move(cols=1)
> VscAnim Command: type(" ** 0.5", return_after=False) # raised to the power of a half
> VscAnim Command: move(cols=1)
> VscAnim Command: type(" / ", return_after=False)     # all over
> VscAnim Command: type("(2 * a)")                     # two times a
> VscAnim Command: type("r2 = (-b - (b**2 - 4 * a * c) ** 0.5) / (2 * a)")
> VscAnim Command: type("print", return_after=False)    # print
> VscAnim Command: type("(", return_after=False)        # parens
> VscAnim Command: type('"r1:", ', return_after=False)  # the label r1, comma
> VscAnim Command: type("r1, ", return_after=False)     # the value of r1
> VscAnim Command: type('"r2:", ', return_after=False)  # the label r2, comma
> VscAnim Command: type("r2")                           # the value of r2
> VscAnim Command: run()
```

Add a check to ensure that VS Code is the current frontmost window. This
allows you to abort the animation by cmd+tab to another window. Example:

```
$ ./vscanim.py intro-to-python.md --start-label=roots-exercise -v
> VscAnim Command: clear_canvas()
> VscAnim Command: type("a = 1")
> VscAnim Command: type("b = -8")
Traceback (most recent call last):
  File "/Users/shad/Workspace/vscanim/./vscanim.py", line 253, in <module>
    main()
  File "/Users/shad/Workspace/vscanim/./vscanim.py", line 249, in main
    eval(line)
  File "<string>", line 1, in <module>
  File "/Users/shad/Workspace/vscanim/./vscanim.py", line 106, in type
    send([KeyStroke(text)])
  File "/Users/shad/Workspace/vscanim/./vscanim.py", line 96, in send
    raise Exception("Aborting execution because VS Code is no longer active")
Exception: Aborting execution because VS Code is no longer active
```